appName: kampus_service

server:
  port: "9000"
  log_level: 3

db:
  host: 127.0.0.1
  port: 5432
  dbname: projek
  user: postgres
  password: root1234

integrations:
  http_dial_timeout_seconds: 5
  http_request_timeout_seconds: 10
  externals:
    http:
      icanhazdadjoke:
        host: "https://icanhazdadjoke.com"
        endpoints:
          random: "/"
          byId: "/j/%s"
